return function(geometry, notes_info)
	return {
		{id = "bg", src = "bg_src", x = 0, y = 0, w = 1920, h = 1080},
		{id = "failedbg", src = "failedbg", x = 0, y = 0, w = 1920, h = 1080},
		{id = "bga_soundonly", src = "soundonly_src", x = 0, y = 0, w = -1, h = -1},
		{id = "head-line", src = "system_src", x = 622, y = 180, w = 250, h = 3},
		{id = "lanes", src = "system_src", x = 0, y = 0, w = 519, h = 856},
		{id = "lanes_line", src = "system_src", x = 3, y = geometry.lane_line_src, w = 513, h = 10},
		{id = "lanes_button", src = "button", x = 0, y = 0, w = 500, h = 100},
		{id = "lanes_button_2P", src = "button", x = 0, y = 150, w = 500, h = 100},
		{id = "lamp_green_v", src = "system_src", x = 660, y = 350, w = 6, h = 14},
		{id = "lamp_duration_v", src = "system_src", x = 670, y = 350, w = 6, h = 14},
		{id = "fast", src = "system_src", x = 33, y = 300, w = 70, h = 19},
		{id = "slow", src = "system_src", x = 1500, y = 350, w = 70, h = 19},
		{id = "fast-lamp", src = "system_src", x = 1500, y = 330, w = 14, h = 19},
		{id = "slow-lamp", src = "system_src", x = 1500, y = 350, w = 14, h = 19},
		{id = "l-rate-DnP", src = "system_src", x = 635, y = 1166, w = 56, h = 18},
		{id = "lamp_music_end", src = "system_src", x = 1350, y = 770, w = 20, h = 40},
		{id = "music_end", src = "system_src", x = 1370, y = 770, w = 130, h = 40},
		{id = "autoplay_tx", src = "system_src", x = 1370, y = 810, w = 250, h = 50},
		{id = "lamp_replay", src = "system_src", x = 1350, y = 860, w = 20, h = 50},
		{id = "replay_tx", src = "system_src", x = 1370, y = 860, w = 160, h = 50},
		{id = "playoption_frame", src = "system_src", x = 900, y = 117, w = 560, h = 179},
		{id = "gauge-DnP", src = "system_src", x = 390, y = 1127, w = 79, h = 36},
		{id = "rate-DnP1", src = "system_src", x = 408, y = 1452, w = 50, h = 50},
		{id = "rate-DnP2", src = "system_src", x = 435, y = 1452, w = 94, h = 37},
		{id = "score-lamp", src = "system_src", x = 600, y = 120, w = 12, h = 60},
		{id = "score-head", src = "score_head", x = 0, y = 0, w = 223, h = 120},
		{id = "notes-head", src = "system_src", x = 1380, y = 750, w = 95, h = 21},
		{id = "lamp-scores", src = "system_src", x = 600, y = 420, w = 10, h = 110},
		{id = "score-mybest-tx", src = "system_src", x = 620, y = 425, w = 83, h = 28},
		{id = "scoregraph-grid", src = "graph-grid", x = 0, y = 0, w = 237, h = 211},
		{id = "graph-best-fp", src = "system_src", x = 615, y = 360, w = 5, h = 20},
		{id = "score-best-fp", src = "system_src", x = 680, y = 340, w = 217, h = 47},
		{id = "songtitle_line", src = "system_src", x = 600, y = 100, w = 610, h = 3},
		{id = "songinfo_frame", src = "system_src", x = 815, y = 10, w = 485, h = 76},
		{id = "songinfo_sp5", src = "system_src", x = 1340, y = 5, w = 80, h = 52},
		{id = "songinfo_sp7", src = "system_src", x = 1340, y = 60, w = 80, h = 52},
		{id = "sp5_lanecover", src = "system_src", x = 2000, y = 0, w = 114, h = 850},
		{id = "songinfo_lamp", src = "system_src", x = 1080, y = 1010, w = 373, h = 36},
		{id = "load-titleline", src = "system_src", x = 530, y = 0, w = 1450, h = 3},
		{id = "load-nostagefile", src = "nostagefile_src", x = 0, y = 0, w = -1, h = -1},
		{id = "BPM-lamp", src = "system_src", x = 600, y = 280, w = 12, h = 60},
		{id = "BPM-head", src = "system_src", x = 622, y = 280, w = 250, h = 60},
		{id = "BPM-bar", src = "BPM-bar", x = 0, y = 0, w = 1027, h = 39},
		{id = "BPM-no-change", src = "system_src", x = 1307, y = 300, w = 80, h = 41},
		{id = "song-time-colon", src = "system_src", x = 0, y = 1400, w = 100, h = 100},
		{id = "song-progress-bar", src = "bar", x = 0, y = 0, w = 70, h = 1080},
		{id = "failed", src = "system_src", x = 1000, y = 1050, w = 440, h = 120},
		{id = "lamp_failed", src = "system_src", x = 950, y = 1050, w = 50, h = 120},
		{id = "fc_glow", src = "system_src", x = 950, y = 1200, w = 513, h = 35},
		{id = "fc_text", src = "system_src", x = 1024, y = 1250, w = 439, h = 60},
		{id = "fc_lamp", src = "system_src", x = 950, y = 1250, w = 74, h = 60},
		{id = "timehispeed", src = "time-hispeed", x = 0, y = 0, w = 280, h = 15},
		{id = "player-icon", src = "p_icon_src", x = 0, y = 0, w = -1, h = -1},
		{id = "lamp-player", src = "p_color_src", x = 0, y = 0, w = -1, h = -1},
		{id = "player-freespace", src = "p_free_src", x = 0, y = 0, w = -1, h = -1},
		{id = "player-line", src = "system_src", x = 1090, y = 980, w = 335, h = 3},
		{id = "judge-pg", src = "judge_src", x = 0, y = 0, w = 191, h = 189, divy = 3, cycle = 120},
		{id = "judge-gr", src = "judge_src", x = 0, y = 122, w = 191, h = 122, divy = 2, cycle = 80},
		{id = "judge-gd", src = "judge_src", x = 0, y = 270, w = 382, h = 61, divx = 2, cycle = 80},
		{id = "judge-bd", src = "judge_src", x = 0, y = 311, w = 382, h = 61, divx = 2, cycle = 80},
		{id = "judge-pr", src = "judge_src", x = 0, y = 440, w = 382, h = 61, divx = 2, cycle = 80},
		{id = "judge-ms", src = "judge_src", x = 0, y = 560, w = 382, h = 61, divx = 2, cycle = 80},
		{id = "keybeam-w", src = "keybeam_src", x = 0, y = 0, w = 50, h = 853},
		{id = "keybeam-b", src = "keybeam_src", x = 50, y = 0, w = 50, h = 853},
		{id = "keybeam-s", src = "keybeam_src", x = 100, y = 0, w = 50, h = 853},
		{id = "note-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.Std_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "note-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.Std_y, w = notes_info.Wh_width, h = notes_info.height},
		{id = "note-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.Std_y, w = notes_info.Sc_width, h = notes_info.height},
		{id = "note-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.Std_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "lnSt-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.lnSt_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "lnSt-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.lnSt_y, w = notes_info.Wh_width, h = notes_info.height},
		{id = "lnSt-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.lnSt_y, w = notes_info.Sc_width, h = notes_info.height},
		{id = "lnSt-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.lnSt_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "lnEn-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.lnEn_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "lnEn-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.lnEn_y, w = notes_info.Wh_width, h = notes_info.height},
		{id = "lnEn-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.lnEn_y, w = notes_info.Sc_width, h = notes_info.height},
		{id = "lnEn-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.lnEn_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "lnBo-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.lnAc_y, w = notes_info.Bl_width, h = notes_info.height * 2, divy = 2, cycle = notes_info.lnCycle},
		{id = "lnBo-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.lnAc_y, w = notes_info.Wh_width, h = notes_info.height * 2, divy = 2, cycle = notes_info.lnCycle},
		{id = "lnBo-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.lnAc_y, w = notes_info.Sc_width, h = notes_info.height * 2, divy = 2, cycle = notes_info.lnCycle},
		{id = "lnBo-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.lnAc_y, w = notes_info.Bl_width, h = notes_info.height * 2, divy = 2, cycle = notes_info.lnCycle},
		{id = "lnAc-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.lnBo_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "lnAc-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.lnBo_y, w = notes_info.Wh_width, h = notes_info.height},
		{id = "lnAc-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.lnBo_y, w = notes_info.Sc_width, h = notes_info.height},
		{id = "lnAc-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.lnBo_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "hcSt-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.hcSt_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "hcSt-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.hcSt_y, w = notes_info.Wh_width, h = notes_info.height},
		{id = "hcSt-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.hcSt_y, w = notes_info.Sc_width, h = notes_info.height},
		{id = "hcSt-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.hcSt_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "hcEn-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.hcEn_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "hcEn-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.hcEn_y, w = notes_info.Wh_width, h = notes_info.height},
		{id = "hcEn-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.hcEn_y, w = notes_info.Sc_width, h = notes_info.height},
		{id = "hcEn-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.hcEn_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "hcAc-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.hcBo_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "hcAc-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.hcBo_y, w = notes_info.Wh_width, h = notes_info.height},
		{id = "hcAc-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.hcBo_y, w = notes_info.Sc_width, h = notes_info.height},
		{id = "hcAc-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.hcBo_y, w = notes_info.Ye_width, h = notes_info.height},
		{id = "hcBo-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.hcAc_y, w = notes_info.Bl_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnCycle},
		{id = "hcBo-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.hcAc_y, w = notes_info.Wh_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnCycle},
		{id = "hcBo-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.hcAc_y, w = notes_info.Sc_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnCycle},
		{id = "hcBo-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.hcAc_y, w = notes_info.Ye_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnCycle},
		{id = "hcDm-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.hcDm_y, w = notes_info.Bl_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnCycle},
		{id = "hcDm-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.hcDm_y, w = notes_info.Wh_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnCycle},
		{id = "hcDm-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.hcDm_y, w = notes_info.Sc_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnCycle},
		{id = "hcDm-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.hcDm_y, w = notes_info.Ye_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnCycle},
		{id = "hcRe-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.hcRe_y, w = notes_info.Bl_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnDamageCycle},
		{id = "hcRe-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.hcRe_y, w = notes_info.Wh_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnDamageCycle},
		{id = "hcRe-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.hcRe_y, w = notes_info.Sc_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnDamageCycle},
		{id = "hcRe-Ye", src = "notes_src", x = notes_info.Ye_x, y = notes_info.hcRe_y, w = notes_info.Ye_width, h = notes_info.height, divy = 2, cycle = notes_info.hcnDamageCycle},
		{id = "mine-Bl", src = "notes_src", x = notes_info.Bl_x, y = notes_info.mine_y, w = notes_info.Bl_width, h = notes_info.height},
		{id = "mine-Wh", src = "notes_src", x = notes_info.Wh_x, y = notes_info.mine_y, w = notes_info.Wh_width, h = notes_info.height},
		{id = "mine-Sc", src = "notes_src", x = notes_info.Sc_x, y = notes_info.mine_y, w = notes_info.Sc_width, h = notes_info.height},
		{id = "section-line", src = "system_src", x = 0, y = 0, w = 1, h = 1},
		{id = "gauge-r1", src = "system_src", x = 900, y = 1000, w = 2, h = 23},
		{id = "gauge-r2", src = "system_src", x = 910, y = 1000, w = 2, h = 23},
		{id = "gauge-r3", src = "system_src", x = 900, y = 1000, w = 2, h = 23},
		{id = "gauge-b1", src = "system_src", x = 905, y = 1000, w = 2, h = 23},
		{id = "gauge-b2", src = "system_src", x = 915, y = 1000, w = 2, h = 23},
		{id = "gauge-b3", src = "system_src", x = 905, y = 1000, w = 2, h = 23},
		{id = "gauge-y1", src = "system_src", x = 900, y = 1025, w = 2, h = 23},
		{id = "gauge-y2", src = "system_src", x = 910, y = 1025, w = 2, h = 23},
		{id = "gauge-y3", src = "system_src", x = 900, y = 1025, w = 2, h = 23},
		{id = "gauge-p1", src = "system_src", x = 900, y = 1025, w = 2, h = 23},
		{id = "gauge-p2", src = "system_src", x = 905, y = 1025, w = 2, h = 23},
		{id = "gauge-p3", src = "system_src", x = 905, y = 1025, w = 2, h = 23},
		{id = "gauge-g1", src = "system_src", x = 925, y = 1000, w = 2, h = 23},
		{id = "gauge-g2", src = "system_src", x = 935, y = 1000, w = 2, h = 23},
		{id = "gauge-g3", src = "system_src", x = 925, y = 1000, w = 2, h = 23},
		{id = "gauge-w1", src = "system_src", x = 923, y = 1025, w = 2, h = 28},
		{id = "gauge-w2", src = "system_src", x = 927, y = 1025, w = 2, h = 28},
		{id = "gauge-w3", src = "system_src", x = 923, y = 1025, w = 2, h = 28},
	}
end
